### ISSUE TITLE
Deprecated "Programming Related" link

### ISSUE THREAD

**Issue by Pdzly** [DC-Resources-Wiki/Discord-Resources-Wiki#20]
The autocode library got shut down
https://discordresources.com/resources/tools/programming#autocode

**Comment by Pdzly** [comment]
https://discordresources.com/resources/moderation#a-guide-to-civil-conversation
this one is broken too

**Comment by JantsoP** [comment]
This is an open project. Anyone can do PR to fix these issues :)
